version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
    allow:
      - dependency-name: "@lit-protocol/lit-node-client"